### PR TITLE
Semaphores

### PR DESCRIPTION
**Pull request by rennergade**
## Description

Fixes # ([issue](https://github.com/Lind-Project/lind_project/issues/321))
NaCl hooks for semaphore functions

### Type of change

- [ x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Tests in rustposix and lind_project

## Checklist:

- [x ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x ] My changes generate no new warnings
- [ x] I have added tests that prove my fix is effective or that my feature works
- [x ] Any dependent changes have been added to a pull request and/or merged in other modules (lind-project, lind-glibc, safeposix-rust)

### CODE REVIEW

**Review by abunav6 — APPROVED** [review]
added semaphores to NaCl syscalls, some formatting changes and code refactoring. LGTM, approving

**Review by justyoyo123 — APPROVED** [review]
These changes that add the necessary hooks in NaCl for the new semaphore functions looks good to me.

**Review by RusherRG — APPROVED** [review]
All the necessary changes with respect to adding the hooks for the `safeposix-rust` syscalls have been made. Also, the bug fixes related to some issues that we found while testing the semaphores seem to be addressed. Nice fixes :partying_face:

**Review by Yaxuan-w — APPROVED** [review]
This modification hooks the system calls in safeposix with NaCl, which is an improvement on semaphore expansion. LGTM so approved.

**Review by kuzeyardabulut — APPROVED** [review]
The code is clean. Eveything seems true so approved.

**Pull request merged**
