### PR TITLE
Added Exit() Interface & RPC

### PR DESCRIPTION
**Pull request by kliu513**

### CODE REVIEW

**Review by jesings — COMMENTED** [review]
This is a straightforward and relatively small commit.
Looks good!

**Comment by rennergade** [comment]
Agree with Jonathan, this looks good!

**Comment by rennergade** [comment]
The other problem with all of these commits is your PR'ing to merge into the master branches, but we want to merge them into the develop branches.

**Comment by kliu513** [comment]
Ohh. So maybe I should have created my branch based on the develop branch?

Nicholas Renner <notifications@github.com> 于 2020年7月31日周五 05:16写道：

**Comment by jesings** [comment]
You should be able to merge develop into your branches without too much hassle, but yes in the future checking out from develop is better

**Comment by kliu513** [comment]
Should I create new PRs in order to merge into the develop branches? I
feel like I can't change the target branch here.

jesings <notifications@github.com> 于2020年7月31日周五 下午1:00写道：

**Comment by jesings** [comment]
just doing a `git merge develop syscall-interception` (or whatever your branch name is on each branch) in the client should work

**Pull request closed without merging**
