### PR TITLE
Implemented pipe2

### PR DESCRIPTION
**Pull request by jesings**

### CODE REVIEW

**Comment by jesings** [comment]
Ok this failed on building glibc...... I'm rerunning but that is weird.

**Comment by jesings** [comment]
Ok I will have to look into that ENOPERM from pipe.

**Comment by rennergade** [comment]
> Ok I will have to look into that ENOPERM from pipe.

Doesn't it need both branches to run correctly?

**Comment by jesings** [comment]
Oh yeah duh, it calls pipe2 from pipe.

**Comment by kapkic** [comment]
Glibc fail happens randomly, building nacl and glibc usually resolves it.
I'm doing a rerun to make sure it's okay.

**Comment by jesings** [comment]
Yep I just ran the tests again manually with both branches and they were good.

**Comment by jesings** [comment]
Yep the failure on the test cases is expected, we should merge the safeposix one in and then we can rerun.

**Comment by jesings** [comment]
Glibc failed again

**Pull request closed without merging**
