### PR TITLE
Adding mknod and fchdir system calls

### PR DESCRIPTION
**Pull request by kuzeyardabulut**

### CODE REVIEW

**Review by RusherRG — COMMENTED** [review]
Just make sure that the syscall number is aligned in `src/shared/platform/lind_platform.h` and `src/trusted/service_runtime/include/bits/nacl_syscalls.h`. 

Everything else looks great :tada:

**Review by justyoyo123 — APPROVED** [review]
These changes look good to me

**Review by kpan2034 — APPROVED** [review]
LGTM 👍

**Review by Yaxuan-w — APPROVED** [review]
looks good to me

**Review by rennergade — APPROVED** [review]
This looks good. You implement the necessary functions to transfer mknod and fcdir between glibc and rustposix, as well as implementing the correct error checking and constants.

**Pull request merged**
